### ISSUE TITLE
dont-go.js:43 Uncaught TypeError: Cannot read property 'setAttribute' of undefined

### ISSUE THREAD

**Issue by hadifarnoud** [mightyCrow/dont-go#5]
I used cdn install. added the script to the head (with async) and other bit of script in the body section.

it throws following error:
```
dont-go.js:43 Uncaught TypeError: Cannot read property 'setAttribute' of undefined
     d	@	dont-go.js:43
```
this is a nodejs app. you can have a look here: http://kamva.ir/

**Comment by hadifarnoud** [comment]
I found out why, we use `serve-favicon` package for our nodejs app. what it does is, it creates a route for serving /favicon.ico from a path it was given. 

we don't have a favicon tag. I just added the tag and it works. 

what if it just adds the tag if it doesn't exist?

**Comment by mightyCrow** [comment]
@hadifarnoud will look into it for future release 👍
