### ISSUE TITLE
title and favicon doesn't change back

### ISSUE THREAD

**Issue by hadifarnoud** [mightyCrow/dont-go#6]
in our blog, we used cdn installation. it does changes title and favicon but it does not change back.

example: http://blog.kamva.ir/shop-builder-new-feature-digital-products/

**Comment by mightyCrow** [comment]
Just fixed it with the latest version 1.0.5

**Comment by hadifarnoud** [comment]
perhaps it takes time to roll out to cdn? I still have the issue

**Comment by hadifarnoud** [comment]
I still have issues: http://blog.kamva.ir/10-easy-ways-increase-ecommerce-sales/

**Comment by mightyCrow** [comment]
@hadifarnoud on the link you provided when I navigate back to the page the favicon & text change back. What browser are you using?

**Comment by hadifarnoud** [comment]
I use Google Chrome

**Comment by Mbotes** [comment]
Hey man, I just tested it out on your site and the favicon and title do change back on both safari and chrome, on chrome it just took a little while longer the first time going back to change the favicon back to normal.

**Comment by mightyCrow** [comment]
![oct-25-2016 17-41-26](https://cloud.githubusercontent.com/assets/18066992/19693016/5e83e71a-9ada-11e6-9ca5-5a376e06530a.gif)

**Comment by hadifarnoud** [comment]
no idea why doesn't change for me. 

![](http://g.recordit.co/AkZBK2tOFm.gif)

**Comment by hadifarnoud** [comment]
so, it started to work just today. was there any change in the code?

**Comment by mightyCrow** [comment]
None 😄, but glad its working now 👍
